// import "../globals.css";

import NavBarAuth from "../../../components/NavBarAuth";
import { getUserDetails, VerifyAuth } from "../../../lib/User";


// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BlogBox",
  description: "Generated by create next app",
};

export default async function AuthRootLayout({ children }) {
  const result = await VerifyAuth();
  const userID = result.user.id;

  const UserData = await getUserDetails(userID);
  return (
    <>
    
    <NavBarAuth user={UserData}/>
      {children}
    
      
    </>
  );
}
