// import "../globals.css";
import NavBarAuth from "../../../components/NavBarAuth";


// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BlogBox",
  description: "Generated by create next app",
};

export default function AuthRootLayout({ children }) {
  return (
    <>
    <div className="mt-3">
    <NavBarAuth />
      {children}
    </div>
      
    </>
  );
}
