
import "./globals.css";
import NavBar from "../../components/NavBar";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BlogBox",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='py-4 px-6 '>
        <NavBar/>{children}</body>
    </html>
  );
}
