import "./globals.css";

import { Toaster } from "sonner";

// const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "BlogBox",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="dark:bg-black scrollbar scrollbar-w-2 scrollbar-thumb-neutral-400 scrollbar-thumb-rounded-2xl dark:scrollbar-thumb-neutral-200">
        
        {children}
        <Toaster richColors position="top-center"/></body>
    </html>
  );
}
